// RN Ready question bank
// Each question: id, cat (category key), q (stem), options[4], correct (index), rationale
const CATEGORIES = {
  pharm:   { name: "Pharmacology",        color: "#C1584B" },
  medsurg: { name: "Med-Surg",            color: "#0F3D3E" },
  matern:  { name: "Maternal & Newborn",  color: "#C99A3D" },
  peds:    { name: "Pediatrics",          color: "#3F7A5C" },
  mh:      { name: "Mental Health",       color: "#6B5B95" },
  fundam:  { name: "Fundamentals",        color: "#4C6B8A" },
  fluid:   { name: "Fluid & Electrolytes",color: "#B4453B" },
  priority:{ name: "Prioritization",      color: "#8A6D3B" }
};

const QUESTIONS = [
{id:1,cat:"pharm",q:"A client is prescribed digoxin. Which assessment finding should the nurse report to the provider before administering the dose?",options:["Apical pulse of 58 bpm","Blood pressure of 128/78","Respiratory rate of 18","Urine output of 50 mL/hr"],correct:0,rationale:"Digoxin slows AV conduction and increases contractility; a heart rate below 60 bpm in an adult signals possible toxicity or excessive bradycardia. Hold the dose and notify the provider."},
{id:2,cat:"pharm",q:"Which lab value is most important to monitor in a client taking warfarin?",options:["Platelet count","INR","Potassium","Hemoglobin A1c"],correct:1,rationale:"INR (International Normalized Ratio) reflects the anticoagulant effect of warfarin; therapeutic range is typically 2-3 for most indications."},
{id:3,cat:"pharm",q:"A client on furosemide should be monitored for which electrolyte imbalance?",options:["Hyperkalemia","Hypokalemia","Hypernatremia","Hypercalcemia"],correct:1,rationale:"Furosemide is a loop diuretic that promotes potassium wasting, putting clients at risk for hypokalemia, which can cause dysrhythmias."},
{id:4,cat:"pharm",q:"The nurse is teaching a client about taking levothyroxine. Which statement indicates correct understanding?",options:["'I'll take it with my breakfast.'","'I'll take it on an empty stomach in the morning.'","'I'll take it at bedtime with milk.'","'I'll double the dose if I miss one.'"],correct:1,rationale:"Levothyroxine should be taken on an empty stomach, 30-60 minutes before breakfast, to maximize and ensure consistent absorption."},
{id:5,cat:"pharm",q:"A client receiving heparin therapy has a critically prolonged aPTT with active bleeding. Which antidote should the nurse anticipate administering?",options:["Vitamin K","Protamine sulfate","Naloxone","Flumazenil"],correct:1,rationale:"Protamine sulfate reverses the anticoagulant effect of heparin. Vitamin K is the antidote for warfarin, not heparin."},
{id:6,cat:"pharm",q:"Which finding would indicate lithium toxicity in a client being treated for bipolar disorder?",options:["Mild hand tremor and thirst","Coarse tremor, ataxia, and vomiting","Dry mouth and mild drowsiness","Increased urination only"],correct:1,rationale:"Coarse tremor, ataxia, vomiting, and confusion indicate lithium toxicity; therapeutic range is narrow (0.6-1.2 mEq/L) and levels should be monitored."},
{id:7,cat:"pharm",q:"A client taking an ACE inhibitor (e.g., lisinopril) develops a persistent dry cough. What should the nurse do?",options:["Reassure the client this is expected and will resolve on its own without follow-up","Report it to the provider as a known adverse effect that may require a medication change","Tell the client to stop taking the medication immediately","Increase fluid intake to suppress the cough"],correct:1,rationale:"A dry, persistent cough is a common ACE inhibitor adverse effect caused by bradykinin accumulation. It should be reported; the provider may switch to an ARB."},
{id:8,cat:"pharm",q:"Before administering IV potassium chloride, which action is essential?",options:["Administer as a rapid IV push","Verify it is diluted and given via infusion pump, never IV push","Mix it with insulin before infusing","Administer intramuscularly if the IV infiltrates"],correct:1,rationale:"IV potassium must always be diluted and administered via infusion pump; undiluted or IV push potassium can cause fatal cardiac arrhythmias."},
{id:9,cat:"pharm",q:"A client is started on metformin for type 2 diabetes. Which teaching point is priority?",options:["Take it with food to reduce GI upset","It will be discontinued before receiving IV contrast dye due to lactic acidosis risk","It commonly causes hypoglycemia when used alone","It should be injected subcutaneously"],correct:1,rationale:"Metformin is typically held 24-48 hours before and after procedures using IV iodinated contrast due to risk of lactic acidosis, especially with renal impairment."},
{id:10,cat:"pharm",q:"Which client statement about taking prednisone long-term requires further teaching?",options:["'I should not stop this medication abruptly.'","'I'll monitor my blood sugar since it can rise.'","'I can stop taking it once I feel better.'","'I should watch for signs of infection since it suppresses my immune system.'"],correct:2,rationale:"Long-term corticosteroids must be tapered gradually to prevent adrenal insufficiency; abrupt discontinuation can be life-threatening."},

{id:11,cat:"medsurg",q:"A client post-thyroidectomy reports tingling around the mouth and in fingertips. What should the nurse suspect?",options:["Hyperkalemia","Hypocalcemia from parathyroid injury","Normal post-anesthesia effect","Hyperglycemia"],correct:1,rationale:"Perioral and finger tingling after thyroidectomy suggests hypocalcemia due to accidental parathyroid gland damage/removal. Assess for Chvostek's and Trousseau's signs."},
{id:12,cat:"medsurg",q:"Which finding in a client with a chest tube indicates an air leak that should be reported?",options:["Gentle bubbling in the water seal chamber with respirations","Continuous bubbling in the water seal chamber","Tidaling that stops with a fully re-expanded lung","Fluctuation with breathing"],correct:1,rationale:"Continuous bubbling in the water seal chamber indicates an air leak in the system, not the expected intermittent tidaling with respirations."},
{id:13,cat:"medsurg",q:"A client with COPD has an oxygen saturation of 90%. The provider orders oxygen at 2L/min via nasal cannula. Why is a low flow rate used?",options:["To prevent oxygen toxicity","To avoid suppressing the hypoxic drive that stimulates breathing in chronic CO2 retainers","Because higher flow damages the nasal mucosa","Low flow is always used regardless of diagnosis"],correct:1,rationale:"Clients with chronic CO2 retention (as in COPD) may rely on hypoxia as their primary respiratory drive; excessive oxygen can blunt this and cause hypoventilation."},
{id:14,cat:"medsurg",q:"The nurse assesses a client 4 hours after abdominal surgery and notes absent bowel sounds. What is the appropriate action?",options:["Notify the provider immediately as an emergency","Document the finding as an expected postoperative finding and reassess later","Insert an NG tube immediately without an order","Encourage the client to eat solid food"],correct:1,rationale:"Absent bowel sounds are expected in the first 24-48 hours post-abdominal surgery due to anesthesia and bowel manipulation; continue routine reassessment."},
{id:15,cat:"medsurg",q:"A client with a new colostomy asks when stoma output is expected to begin. What should the nurse explain?",options:["Immediately after surgery","Typically within 2-4 days as bowel motility returns","Not for at least 2 weeks","Only after starting a regular diet"],correct:1,rationale:"Peristalsis typically returns and stoma output begins within 2-4 days postoperatively as bowel function resumes."},
{id:16,cat:"medsurg",q:"Which is an early sign of compartment syndrome in a client with a fractured leg in a cast?",options:["Pain out of proportion to injury, unrelieved by analgesics","Warm, pink toes","Palpable pedal pulses","Absence of swelling"],correct:0,rationale:"Pain that is disproportionate to the injury and not relieved by opioids is the earliest and most reliable sign of compartment syndrome; pulselessness is a late sign."},
{id:17,cat:"medsurg",q:"A client with cirrhosis develops asterixis and confusion. What condition does the nurse suspect?",options:["Hepatic encephalopathy from elevated ammonia","Hypoglycemia","Alcohol withdrawal only","Esophageal varices bleeding"],correct:0,rationale:"Asterixis (flapping tremor) and altered mental status in cirrhosis indicate hepatic encephalopathy, caused by the liver's inability to clear ammonia."},
{id:18,cat:"medsurg",q:"Which position is best for a client immediately after a liver biopsy?",options:["Left side-lying","Right side-lying, with a pillow against the site","Prone","High Fowler's"],correct:1,rationale:"Lying on the right side with pressure applied against the biopsy site helps tamponade the puncture site and reduce bleeding risk."},
{id:19,cat:"medsurg",q:"A client with a new tracheostomy develops bright red bleeding from the stoma. What is the nurse's priority action?",options:["Document and continue routine care","Notify the provider immediately; this may indicate a tracheoinnominate artery fistula","Increase suctioning frequency","Apply a warm compress"],correct:1,rationale:"Bright red bleeding from a tracheostomy stoma, especially pulsatile, can indicate erosion into the innominate artery — a rare but life-threatening emergency requiring immediate notification."},
{id:20,cat:"medsurg",q:"Which teaching is appropriate for a client newly diagnosed with Guillain-Barré syndrome regarding disease course?",options:["Symptoms will remain confined to the hands only","Ascending muscle weakness may progress and requires close respiratory monitoring","The condition is permanent and progressive with no recovery","No monitoring is needed since it resolves in hours"],correct:1,rationale:"Guillain-Barré typically causes ascending paralysis that can progress to respiratory muscles; frequent monitoring of respiratory status (vital capacity) is essential."},

{id:21,cat:"matern",q:"A laboring client's fetal heart rate tracing shows late decelerations. What is the nurse's priority intervention?",options:["Increase the oxytocin infusion rate","Reposition the client to left lateral, administer oxygen, and notify the provider","Have the client ambulate immediately","Document and continue monitoring only"],correct:1,rationale:"Late decelerations suggest uteroplacental insufficiency. Priority actions include repositioning (left lateral), administering oxygen, stopping oxytocin if infusing, and notifying the provider."},
{id:22,cat:"matern",q:"Which finding in a postpartum client 2 hours after vaginal delivery requires immediate nursing action?",options:["Fundus firm, midline, at the umbilicus","Moderate lochia rubra","A boggy uterus displaced to the right of midline","Mild afterpains"],correct:2,rationale:"A boggy, displaced uterus suggests a full bladder or uterine atony, risking postpartum hemorrhage; the nurse should massage the fundus and assist with voiding."},
{id:23,cat:"matern",q:"A client at 32 weeks gestation reports a sudden gush of fluid and the nurse suspects rupture of membranes. What is priority?",options:["Assess fetal heart rate immediately to rule out cord prolapse","Have the client walk to the bathroom to confirm","Delay assessment until the provider arrives","Encourage the client to eat"],correct:0,rationale:"After suspected rupture of membranes, immediate fetal heart rate assessment is priority to rule out umbilical cord prolapse, an obstetric emergency, especially with a non-engaged presenting part."},
{id:24,cat:"matern",q:"Which client is at highest risk for magnesium sulfate toxicity requiring close monitoring during administration for preeclampsia?",options:["A client with normal renal function","A client with decreased urine output and diminished deep tendon reflexes","A client with a respiratory rate of 18","A client who is alert and oriented"],correct:1,rationale:"Magnesium sulfate is excreted renally; decreased urine output allows magnesium to accumulate. Diminished/absent deep tendon reflexes are an early sign of toxicity, which can progress to respiratory depression."},
{id:25,cat:"matern",q:"A newborn's blood glucose is 35 mg/dL at 1 hour of life. What is the priority nursing action?",options:["Feed the newborn (breast milk or formula) and recheck glucose","Withhold feeding and recheck in 4 hours","Administer IV dextrose immediately without further assessment","No action needed, this is normal"],correct:0,rationale:"For mild hypoglycemia, early feeding is the first-line intervention, followed by rechecking glucose per protocol; IV dextrose is reserved for severe or symptomatic hypoglycemia."},
{id:26,cat:"matern",q:"Which assessment finding in a newborn is an expected variation and not cause for concern?",options:["Central cyanosis at rest","Acrocyanosis of the hands and feet in the first 24 hours","Grunting with every breath","Sternal retractions at rest"],correct:1,rationale:"Acrocyanosis (bluish hands/feet with pink central body) is a normal newborn finding related to immature peripheral circulation and typically resolves within 24-48 hours."},

{id:27,cat:"peds",q:"A 2-year-old is admitted with suspected epiglottitis. Which action should the nurse avoid?",options:["Keeping the child calm and upright","Examining the throat with a tongue depressor","Preparing for possible emergency intubation","Allowing the parent to stay with the child"],correct:1,rationale:"Throat examination or any oral manipulation can trigger complete airway obstruction in epiglottitis and should be avoided; keep the child calm and prepare for emergency airway management."},
{id:28,cat:"peds",q:"Which is a classic sign of intussusception in an infant?",options:["Painless bloody stools throughout the day","Currant jelly stools with intermittent, severe abdominal pain","Chronic constipation only","Projectile vomiting after every feeding from birth"],correct:1,rationale:"Intussusception classically presents with sudden episodic abdominal pain, drawing legs up, vomiting, and 'currant jelly' stools from mixed blood and mucus."},
{id:29,cat:"peds",q:"A child with suspected bacterial meningitis is admitted. Which precaution should the nurse implement first?",options:["Contact precautions","Droplet precautions until 24 hours of effective antibiotics","Airborne precautions","No isolation needed"],correct:1,rationale:"Bacterial meningitis (e.g., N. meningitidis, H. influenzae) requires droplet precautions until the client has received at least 24 hours of appropriate antibiotic therapy."},
{id:30,cat:"peds",q:"Which finding is most consistent with a diagnosis of pyloric stenosis in an infant?",options:["Bilious vomiting with abdominal distension","Non-bilious, projectile vomiting after feeding with a palpable olive-shaped mass","Bloody diarrhea","Low-grade fever with rash"],correct:1,rationale:"Pyloric stenosis presents with non-bilious projectile vomiting shortly after feeding, hunger after vomiting, and a palpable olive-shaped mass in the epigastric area."},
{id:31,cat:"peds",q:"A child with a diagnosis of Kawasaki disease is at greatest risk for which complication if untreated?",options:["Coronary artery aneurysm","Renal failure","Hearing loss","Seizures"],correct:0,rationale:"Kawasaki disease causes systemic vasculitis; the most serious complication is coronary artery aneurysm, which is why IVIG and aspirin therapy are initiated promptly."},
{id:32,cat:"peds",q:"The nurse is caring for a child in sickle cell crisis. Which intervention is priority?",options:["Apply ice packs to painful joints","Administer IV fluids and analgesics, and encourage warmth to painful areas","Restrict oral fluids to prevent overload","Encourage strenuous activity to improve circulation"],correct:1,rationale:"During vaso-occlusive crisis, hydration (IV fluids) and adequate pain management are priorities; warmth (not ice) promotes vasodilation and reduces further sickling."},

{id:33,cat:"mh",q:"A client with major depressive disorder who was previously withdrawn suddenly appears calm and gives away personal belongings. What should the nurse suspect?",options:["The client's depression is resolving","The client may be at increased risk for suicide and has made a decision to act","The client wants to be discharged early","This is unrelated behavior"],correct:1,rationale:"A sudden sense of calm or peace after a period of depression, along with giving away possessions, can indicate the client has decided on a suicide plan. This requires immediate safety assessment."},
{id:34,cat:"mh",q:"Which nursing action is priority when caring for a client experiencing acute alcohol withdrawal?",options:["Encourage the client to detox without medication","Monitor for and treat withdrawal symptoms per protocol (e.g., CIWA scale), including seizure precautions","Restrict all fluids","Avoid checking vital signs to reduce stimulation"],correct:1,rationale:"Alcohol withdrawal can progress to delirium tremens and seizures; the nurse should monitor using a standardized scale (CIWA-Ar), administer benzodiazepines as ordered, and maintain seizure precautions."},
{id:35,cat:"mh",q:"A client with borderline personality disorder is splitting staff by praising one nurse and criticizing another. What is the best nursing approach?",options:["Staff should discuss the client individually without a consistent plan","Maintain consistent, clear limits and communicate as a team using a unified care plan","Avoid the client to prevent conflict","Allow the client to choose which staff provide care"],correct:1,rationale:"Consistency among staff and a unified, clearly communicated care plan helps prevent manipulation/splitting behaviors common in borderline personality disorder."},
{id:36,cat:"mh",q:"Which statement by a client taking an MAOI (e.g., phenelzine) indicates understanding of dietary teaching?",options:["'I can eat aged cheeses and cured meats freely.'","'I need to avoid tyramine-rich foods like aged cheese and cured meats to prevent a hypertensive crisis.'","'I should increase my salt intake.'","'There are no dietary restrictions with this medication.'"],correct:1,rationale:"MAOIs inhibit the breakdown of tyramine; consuming tyramine-rich foods can cause a life-threatening hypertensive crisis. Clients must avoid aged cheeses, cured meats, and fermented foods."},
{id:37,cat:"mh",q:"A client in a manic episode is being admitted. Which environment modification is most appropriate?",options:["A stimulating environment with group activities","A low-stimulation environment with minimal noise and distraction","Bright lighting and loud music to help expend energy","No modification needed"],correct:1,rationale:"Clients in a manic episode benefit from a low-stimulation environment to reduce escalation of hyperactivity and help prevent exhaustion."},

{id:38,cat:"fundam",q:"Before administering any medication, which are the nurse's priority 'rights' to verify?",options:["Right patient, drug, dose, route, and time","Right diagnosis and prognosis only","Right insurance coverage","Right family member present"],correct:0,rationale:"The core 'rights' of medication administration include right patient, drug, dose, route, and time (with documentation and reason often added as additional rights)."},
{id:39,cat:"fundam",q:"Which technique is correct when performing hand hygiene with soap and water?",options:["Rub hands together for at least 15-20 seconds with friction covering all surfaces","A quick 2-3 second rinse is sufficient","Use hot water only, no need for friction","Dry hands by waving them in the air only"],correct:0,rationale:"CDC guidelines recommend washing hands with soap and water for at least 15-20 seconds, ensuring friction across all surfaces including between fingers and under nails."},
{id:40,cat:"fundam",q:"A client is on contact precautions. Which PPE is required when entering the room?",options:["Gown and gloves","N95 respirator only","Surgical mask only","No PPE required"],correct:0,rationale:"Contact precautions (e.g., for MRSA, C. diff) require gown and gloves to prevent transmission via direct contact or contaminated surfaces."},
{id:41,cat:"fundam",q:"When repositioning an immobile client, which action best prevents pressure injury?",options:["Reposition every 4 hours regardless of skin condition","Reposition at least every 2 hours and assess skin with each turn","Only reposition when the client requests it","Massage reddened bony prominences vigorously"],correct:1,rationale:"Standard practice is repositioning at least every 2 hours with skin assessment at each turn; vigorous massage of reddened areas can cause further tissue damage and should be avoided."},
{id:42,cat:"fundam",q:"Which is the correct order of steps when donning PPE?",options:["Gloves, gown, mask, eye protection","Gown, mask/respirator, eye protection, gloves","Mask, gloves, gown, eye protection","Eye protection, gloves, gown, mask"],correct:1,rationale:"The CDC-recommended donning sequence is: gown first, then mask/respirator, then eye protection/goggles, and gloves last."},
{id:43,cat:"fundam",q:"A client's wound has a Stage 2 pressure injury. Which description matches this stage?",options:["Intact skin with non-blanchable redness","Partial-thickness skin loss with exposed dermis, possibly a shallow open ulcer or blister","Full-thickness tissue loss with visible fat","Full-thickness loss with exposed bone, tendon, or muscle"],correct:1,rationale:"Stage 2 pressure injuries involve partial-thickness skin loss with exposed dermis, presenting as a shallow open ulcer or intact/ruptured serum-filled blister."},

{id:44,cat:"fluid",q:"A client has a serum potassium of 6.2 mEq/L. Which ECG change should the nurse anticipate?",options:["Flattened T waves","Peaked T waves and widened QRS","Prominent U waves","Shortened PR interval only"],correct:1,rationale:"Hyperkalemia classically produces peaked, tented T waves and, as it worsens, a widened QRS complex — both are cardiac emergencies requiring prompt treatment."},
{id:45,cat:"fluid",q:"Which client is at greatest risk for developing hyponatremia?",options:["A client receiving excessive free water via tube feeding without adequate sodium","A client with a high-sodium diet","A client who is NPO and receiving isotonic IV fluids","A client with diabetes insipidus"],correct:0,rationale:"Excess free water intake without proportional sodium (as with dilute tube feedings or excess D5W) dilutes serum sodium, causing hyponatremia."},
{id:46,cat:"fluid",q:"A client with a serum calcium of 6.5 mg/dL should be assessed for which finding?",options:["Chvostek's and Trousseau's signs (tetany)","Constipation and lethargy","Bradycardia and shortened QT interval","Polyuria"],correct:0,rationale:"Hypocalcemia causes neuromuscular excitability, manifesting as tetany, positive Chvostek's sign (facial twitching) and Trousseau's sign (carpal spasm with BP cuff inflation)."},
{id:47,cat:"fluid",q:"Which client is at highest risk for fluid volume overload?",options:["A client with heart failure receiving IV fluids","A client with diarrhea for 3 days","A client who is NPO for surgery","A client with a draining fistula"],correct:0,rationale:"Clients with heart failure have reduced cardiac reserve; administering IV fluids increases risk of fluid overload and pulmonary edema."},
{id:48,cat:"fluid",q:"A client has metabolic acidosis with a pH of 7.28 and bicarbonate of 16 mEq/L. Which respiratory pattern would the nurse expect as compensation?",options:["Slow, shallow breathing","Kussmaul respirations (deep, rapid breathing)","Breath-holding","Normal respiratory rate"],correct:1,rationale:"In metabolic acidosis, the body compensates by increasing respiratory rate and depth (Kussmaul respirations) to blow off CO2 and raise pH."},

{id:49,cat:"priority",q:"The nurse is assigned four clients at the start of the shift. Which client should be assessed first?",options:["A client 2 days post-op requesting pain medication","A client with a new onset of chest pain and diaphoresis","A client due for a routine dressing change","A client waiting for discharge teaching"],correct:1,rationale:"Using the ABC/urgency framework, a client with new chest pain and diaphoresis suggests a potential cardiac event and takes priority for immediate assessment."},
{id:50,cat:"priority",q:"Using the ABC framework, which client should the nurse see first?",options:["A client with a respiratory rate of 8 and decreased responsiveness","A client with a blood glucose of 180 mg/dL","A client reporting mild nausea","A client requesting a warm blanket"],correct:0,rationale:"Airway and breathing take top priority; a respiratory rate of 8 with decreased responsiveness signals impending respiratory failure requiring immediate intervention."},
{id:51,cat:"priority",q:"The nurse receives report on four clients. Which should be seen first after report?",options:["A client with stable vital signs post-op day 3","A client with a new tracheostomy who is anxious and has increased secretions","A client scheduled for discharge in 2 hours","A client awaiting a routine lab draw"],correct:1,rationale:"A new tracheostomy with increased secretions and anxiety raises concern for airway compromise, making this the priority client to assess first."},
{id:52,cat:"priority",q:"When delegating tasks to unlicensed assistive personnel (UAP), which task is appropriate to delegate?",options:["Assessing a new client's pain level and formulating a plan","Administering IV medications","Assisting a stable client with ambulation","Teaching a client about a new medication"],correct:2,rationale:"UAPs can perform basic care tasks such as assisting stable clients with ambulation. Assessment, medication administration, and teaching require licensed nurse judgment and cannot be delegated."},
{id:53,cat:"priority",q:"A nurse is caring for multiple clients. Which client requires the most immediate follow-up?",options:["A client with a temperature of 100.4°F 12 hours post-op","A client whose urine output has been 15 mL/hr for the past 2 hours","A client reporting a pain level of 4/10","A client with dry mucous membranes who is drinking fluids well"],correct:1,rationale:"Urine output below 30 mL/hr for 2+ hours indicates possible acute kidney injury or hypoperfusion and requires prompt follow-up and provider notification."},

{id:54,cat:"medsurg",q:"A client with a diagnosis of Addison's disease is at risk for which electrolyte imbalance during an addisonian crisis?",options:["Hyperkalemia and hyponatremia","Hypokalemia and hypernatremia","Hypercalcemia only","No electrolyte changes expected"],correct:0,rationale:"Addison's disease (adrenal insufficiency) results in decreased aldosterone, causing sodium loss (hyponatremia) and potassium retention (hyperkalemia), which can be severe during crisis."},
{id:55,cat:"medsurg",q:"Which finding indicates a client with a below-knee amputation may be developing a hematoma requiring intervention?",options:["Mild residual limb swelling","Increasing size, tightness, and ecchymosis of the residual limb dressing","Phantom limb sensation","Slight serosanguineous drainage"],correct:1,rationale:"Increasing swelling, tightness, and bruising under the dressing suggest hematoma formation, which can compromise healing and requires provider notification."},
{id:56,cat:"medsurg",q:"A client with myasthenia gravis reports increasing weakness after taking pyridostigmine. The nurse should recognize this may indicate:",options:["Myasthenic crisis requiring more medication only","Possible cholinergic crisis from excess medication, requiring prompt evaluation","A normal medication response requiring no action","Signs of full recovery"],correct:1,rationale:"Worsening weakness shortly after taking anticholinesterase medication can indicate cholinergic crisis (from excess medication) versus myasthenic crisis (too little); differentiation via tensilon testing/clinical evaluation is needed before further dosing."},

{id:57,cat:"pharm",q:"A client is prescribed both a nonsteroidal anti-inflammatory drug (NSAID) and warfarin. What is the primary concern?",options:["Increased risk of bleeding due to additive anticoagulant/antiplatelet effects","Decreased effectiveness of warfarin","No interaction of concern","Increased risk of hyperglycemia"],correct:0,rationale:"NSAIDs inhibit platelet function and can irritate the GI mucosa; combined with warfarin's anticoagulant effect, this significantly increases bleeding risk."},
{id:58,cat:"pharm",q:"Which instruction should the nurse give a client starting an SSRI (e.g., sertraline) for depression?",options:["Expect immediate mood improvement within 1-2 days","Full therapeutic effect may take 4-6 weeks; continue taking as prescribed even if not feeling better right away","Stop the medication if no effect is seen in 3 days","SSRIs are only effective when taken as needed"],correct:1,rationale:"SSRIs typically take 4-6 weeks to reach full therapeutic effect. Clients should be counseled to continue the medication and report any worsening mood or suicidal ideation, especially early in treatment."},
{id:59,cat:"pharm",q:"A client receiving vancomycin reports flushing, redness, and itching of the face and neck during infusion. What does the nurse suspect?",options:["Anaphylaxis requiring epinephrine","'Red man syndrome' related to infusion rate, requiring the infusion to be slowed","A normal expected reaction requiring no action","An allergic reaction requiring immediate discontinuation and never re-administering"],correct:1,rationale:"Red man syndrome results from histamine release related to rapid vancomycin infusion, not a true allergy. Slowing the infusion rate typically resolves symptoms."},
{id:60,cat:"pharm",q:"Which client teaching is important for someone newly prescribed a bisphosphonate (e.g., alendronate) for osteoporosis?",options:["Take it lying down at bedtime","Take it first thing in the morning with a full glass of water, remain upright for 30-60 minutes, and avoid food afterward for that time","Take it with food to prevent nausea","Take it right before bed with milk"],correct:1,rationale:"Bisphosphonates require an empty stomach with a full glass of plain water, remaining upright for at least 30-60 minutes, to reduce esophageal irritation and improve absorption."},

{id:61,cat:"matern",q:"A client is diagnosed with gestational diabetes. Which statement indicates the need for further teaching?",options:["'I'll check my blood sugar as directed and follow the meal plan.'","'This means my baby will definitely have diabetes at birth.'","'I may need insulin if diet and exercise don't control my glucose.'","'I'll need follow-up glucose testing after delivery.'"],correct:1,rationale:"Gestational diabetes does not mean the newborn will have diabetes at birth, though the newborn is at risk for hypoglycemia after delivery due to fetal hyperinsulinemia; this statement reflects a misunderstanding."},
{id:62,cat:"matern",q:"Which finding in a client with preeclampsia indicates progression to severe features?",options:["Blood pressure of 138/88","Mild ankle edema","Blood pressure of 168/110 with visual disturbances and epigastric pain","Trace proteinuria"],correct:2,rationale:"Severe features of preeclampsia include BP ≥160/110, visual disturbances, epigastric or RUQ pain (suggesting liver involvement), and other signs of end-organ dysfunction."},
{id:63,cat:"matern",q:"A client is 4 hours postpartum after a cesarean birth. Which assessment finding requires immediate notification of the provider?",options:["Fundus firm at the umbilicus","Pad saturated with blood in 15 minutes","Mild incisional pain rated 4/10","Scant lochia rubra"],correct:1,rationale:"Saturating a pad within 15 minutes indicates excessive postpartum hemorrhage and requires immediate assessment and provider notification."},

{id:64,cat:"peds",q:"Which developmental milestone would the nurse expect in a healthy 9-month-old?",options:["Walking independently","Sitting without support and beginning to pull to stand","Speaking in full sentences","Riding a tricycle"],correct:1,rationale:"By 9 months, infants typically sit well without support and begin pulling to stand; independent walking usually emerges around 12-15 months."},
{id:65,cat:"peds",q:"A child with croup has stridor at rest and increased work of breathing. What is the priority nursing action?",options:["Encourage the child to lie flat","Provide cool mist/humidified air and keep the child calm, and prepare for possible nebulized epinephrine","Give the child something to eat to distract them","Delay treatment until symptoms worsen"],correct:1,rationale:"For croup with stridor at rest, cool humidified air and keeping the child calm reduce airway irritation; nebulized epinephrine may be needed for significant respiratory distress."},
{id:66,cat:"peds",q:"Which is a priority nursing consideration for a child with nephrotic syndrome?",options:["Restricting fluids at all times","Monitoring for infection due to loss of immunoglobulins in urine, and monitoring edema and protein loss","Encouraging high-sodium foods","No dietary modifications needed"],correct:1,rationale:"Nephrotic syndrome causes significant proteinuria including immunoglobulin loss, increasing infection risk; nurses also monitor edema, weight, and abdominal girth."},

{id:67,cat:"mh",q:"A client with generalized anxiety disorder is prescribed buspirone. Which teaching point is important?",options:["It works immediately for acute anxiety attacks","Full therapeutic effect may take 2-4 weeks; it is not for immediate/PRN use during acute anxiety","It is highly sedating and should be taken at bedtime only","It is a controlled substance with high abuse potential like benzodiazepines"],correct:1,rationale:"Unlike benzodiazepines, buspirone is not effective for acute anxiety and takes 2-4 weeks for full effect; it also has low abuse potential and is not habit-forming."},
{id:68,cat:"mh",q:"A client with schizophrenia reports auditory hallucinations telling them to harm themselves. What is the nurse's priority?",options:["Ignore the hallucinations since they are not real","Assess for safety, ask directly about intent, and implement appropriate precautions","Argue with the client that the voices aren't real","Leave the client alone to calm down"],correct:1,rationale:"Command hallucinations involving self-harm require direct safety assessment and appropriate precautions; the nurse should acknowledge the client's experience without reinforcing the hallucination as real."},
{id:69,cat:"mh",q:"Which is a therapeutic communication technique the nurse should use with a client in acute distress?",options:["Giving advice on what the client should do","Using open-ended questions and reflecting feelings back to the client","Changing the subject to something more pleasant","Offering reassurance like 'everything will be fine'"],correct:1,rationale:"Open-ended questions and reflection encourage the client to explore and express feelings; false reassurance and advice-giving are generally non-therapeutic."},

{id:70,cat:"fundam",q:"When measuring a client's blood pressure, which factor could cause a falsely elevated reading?",options:["Using a cuff that is too large","Using a cuff that is too small for the arm circumference","Supporting the arm at heart level","Allowing the client to rest 5 minutes before measurement"],correct:1,rationale:"A cuff that is too small for the arm produces falsely elevated blood pressure readings; a cuff too large can cause falsely low readings."},
{id:71,cat:"fundam",q:"Which is the correct technique for administering an intramuscular injection into the ventrogluteal site?",options:["90-degree angle using the palm of the hand to locate landmarks, injecting into the gluteus medius","45-degree angle into the deltoid","Subcutaneous angle of 15 degrees","Injection directly into the sciatic nerve area"],correct:0,rationale:"The ventrogluteal site is located using the palm on the greater trochanter with fingers spread to landmarks; injection is given at a 90-degree angle into the gluteus medius, avoiding major nerves and vessels."},
{id:72,cat:"fundam",q:"A client has an order for strict intake and output. Which items should be included in output measurement?",options:["Only urine","Urine, emesis, wound drainage, and liquid stool","Only IV fluids given","Solid food intake"],correct:1,rationale:"Strict I&O output includes all fluid losses: urine, emesis, wound/drain output, and liquid stool, in addition to insensible losses when relevant."},

{id:73,cat:"fluid",q:"A client with heart failure and fluid restriction asks why fluid is limited. What is the nurse's best explanation?",options:["Fluid restriction has no real benefit","Limiting fluid reduces the workload on the heart and helps prevent worsening fluid overload/edema","Fluid restriction cures heart failure","Only sodium needs to be restricted, not fluids"],correct:1,rationale:"In heart failure, excess fluid increases preload and cardiac workload; fluid restriction (along with sodium restriction) helps manage symptoms and prevent decompensation."},
{id:74,cat:"fluid",q:"Which client is most at risk for developing respiratory acidosis?",options:["A client hyperventilating from anxiety","A client with a narcotic overdose causing respiratory depression","A client with diabetic ketoacidosis","A client with prolonged vomiting"],correct:1,rationale:"Respiratory depression (e.g., from opioid overdose) causes CO2 retention, leading to respiratory acidosis due to inadequate ventilation."},
{id:75,cat:"fluid",q:"A client's ABG shows pH 7.50, PaCO2 30, HCO3 24. How should the nurse interpret this?",options:["Metabolic acidosis, uncompensated","Respiratory alkalosis, uncompensated","Metabolic alkalosis, compensated","Respiratory acidosis, compensated"],correct:1,rationale:"Elevated pH (alkalosis) with low PaCO2 and normal HCO3 indicates uncompensated respiratory alkalosis, often caused by hyperventilation."},

{id:76,cat:"priority",q:"A charge nurse is making assignments. Which client is most appropriate to assign to a newly licensed nurse?",options:["A client in active labor with a non-reassuring fetal heart tracing","A stable client 3 days post-op requiring routine dressing changes","A client with a fresh tracheostomy and unstable airway","A client in active DKA requiring an insulin drip titration"],correct:1,rationale:"A stable post-op client with routine care needs is appropriate for a newly licensed nurse; complex, unstable, or high-acuity clients should be assigned to more experienced staff."},
{id:77,cat:"priority",q:"Which client should the nurse assess as the priority after receiving change-of-shift report?",options:["A client with a pain score of 3/10 requesting medication","A client who just returned from a cardiac catheterization with a new cool, pale, pulseless extremity","A client waiting for a scheduled ambulation","A client with a stable chronic wound dressing due for change"],correct:1,rationale:"A cool, pale, pulseless extremity after cardiac catheterization suggests arterial occlusion, a vascular emergency requiring immediate assessment and intervention."},
{id:78,cat:"priority",q:"Applying Maslow's hierarchy of needs, which client need should the nurse address first?",options:["A client wanting to discuss discharge plans","A client with an oxygen saturation of 88% and labored breathing","A client requesting to see a chaplain","A client wanting privacy for a phone call"],correct:1,rationale:"Physiological needs, particularly oxygenation, take priority over psychosocial or safety needs per Maslow's hierarchy; the client with hypoxia should be assessed immediately."},

{id:79,cat:"medsurg",q:"A client is diagnosed with syndrome of inappropriate antidiuretic hormone (SIADH). What finding should the nurse expect?",options:["Dilute urine and hypernatremia","Concentrated urine, fluid retention, and hyponatremia","Excessive urine output and dehydration","Hypokalemia and metabolic alkalosis"],correct:1,rationale:"SIADH causes excess ADH secretion, leading to water retention, concentrated urine, and dilutional hyponatremia despite normal or increased fluid volume."},
{id:80,cat:"medsurg",q:"Which is a priority nursing action for a client immediately after a cardiac catheterization via the femoral approach?",options:["Ambulate the client immediately","Keep the affected leg straight and monitor the insertion site for bleeding/hematoma","Elevate the head of bed to 90 degrees immediately","Remove the pressure dressing after 10 minutes"],correct:1,rationale:"After femoral catheterization, the leg should be kept straight and immobilized per protocol, with frequent monitoring of the insertion site, distal pulses, and vital signs to detect bleeding or hematoma."},
{id:81,cat:"medsurg",q:"A client with acute pancreatitis is admitted. Which finding is consistent with this diagnosis?",options:["Severe epigastric pain radiating to the back, with elevated lipase/amylase","Right lower quadrant pain with rebound tenderness","Painless jaundice only","Substernal chest pain radiating to the jaw"],correct:0,rationale:"Acute pancreatitis classically presents with severe epigastric pain radiating to the back, often worse after eating, along with elevated serum lipase and amylase."},

{id:82,cat:"pharm",q:"A client is prescribed clopidogrel after stent placement. What is important patient teaching?",options:["It can be stopped as soon as symptoms improve","Do not stop the medication without consulting the cardiologist, due to stent thrombosis risk","It should be taken only when chest pain occurs","No bleeding precautions are necessary"],correct:1,rationale:"Clopidogrel prevents stent thrombosis; abrupt discontinuation without provider guidance significantly increases the risk of life-threatening clot formation in the stent."},
{id:83,cat:"pharm",q:"Which client would be most appropriate to receive a beta-blocker with caution or require closer monitoring?",options:["A client with hypertension only","A client with asthma or reactive airway disease","A client with tachycardia","A client with anxiety"],correct:1,rationale:"Non-selective beta-blockers can cause bronchoconstriction and are used cautiously in clients with asthma or COPD due to risk of bronchospasm."},

{id:84,cat:"fundam",q:"Which action best demonstrates the nurse applying the principle of client autonomy?",options:["Making decisions for the client based on what the nurse believes is best","Ensuring the client has adequate information and respecting their right to make their own healthcare decisions","Overriding a client's refusal of treatment for their own good","Withholding information that may upset the client"],correct:1,rationale:"Autonomy is an ethical principle respecting a client's right to make informed decisions about their own care, which requires providing adequate information."},
{id:85,cat:"fundam",q:"A client refuses a scheduled medication. What is the nurse's best initial action?",options:["Administer it anyway since it was ordered","Explore the reason for refusal, provide education, and respect the client's right to refuse after being informed","Document refusal without further discussion","Have a family member convince the client"],correct:1,rationale:"Competent clients have the right to refuse treatment. The nurse should explore concerns, provide relevant information, document the refusal and education provided, and notify the provider as needed."}
];
